project-codeblue/CodeBlue

README.md
=> feat: update readme : 권용재

config/app.config.ts, package-lock.json, package.json, src/commons/utils/kakao-map.service.ts, src/reports/reports.module.ts, src/reports/service/reports.service.ts, src/requests/requests.repository.ts
commons/utils에 카카오맵 api를 불러오는 service를 등록했습니다.
updatePatientLocation (url: /report/:report_id) patch api를 호출하면 "site"에 경기도, 서울특별시 등등 사용자 좌표값에 따른 지역명이 함께 response로 출력됩니다.
Related: #8
=> feat: 카카오맵 api 사용해서 좌표 -> 주소 변환

src/commons/utils/kakao-map.service.ts, src/reports/service/reports.service.ts
* src/commons/utils에 kakao-map.service.ts getDrivingDuration에 해당 코드 넣어뒀습니다. 
* 카카오 rest api key 환경변수에 추가하시고 npm install하신 후 테스트 해보시면 됩니다!
=> feat: 두 좌표값 자동차로 이동 거리 duration

src/commons/middlewares/crawling.ts, src/commons/middlewares/medicalOpenAPI.ts, src/hospitals/controller/hospitals.controller.ts, src/hospitals/service/hospitals.service.ts
- getLocalHospitals API의 경우 "hospital/local?site=경기도" 와 같이 URL에 site로 쿼리를 보내면 해당 지역에 대한 병상 데이터를 반환합니다.
- getNearbyHospitals API의 경우 "hospital/nearBy?emogList=A1100010&emogList=A1100011&emogList=A1400015" 와 같은 형태로 URL에 emogList를 보내면 string배열로 받아 해당 병원에 대한 병상 데이터를 조회합니다. (크롤링 대상 사이트 특성으로 최대 12곳까지 가능)
- 기타 코드 리팩토링
=> refactor: hospitals 및 크롤링 기능 refactoring

package-lock.json, package.json, src/commons/middlewares/crawling.ts, src/hospitals/controller/hospitals.controller.spec.ts, src/hospitals/controller/hospitals.controller.ts, src/hospitals/service/hospitals.service.ts, src/reports/controller/reports.controller.ts, src/reports/reports.entity.ts, src/reports/reports.repository.ts, src/reports/service/reports.service.ts, src/requests/requests.repository.ts
- 검색 API에 지역 조건 추가
- Report 더미데이터 생성 API 구현
- 병원 (추천) 조회 API 통합 구현 (기존 getNearbyHospitals의 기능을 getRecommendedHospitals API 통합하여 구현)
- hospitals controller 단위 테스트 구현
=> feat: 검색, Report 및 병원 관련 API 작업

.prettierrc
첫 pr test 
pr close 하셔도 상관없습니다!
=> [style] prettier + eslint 형식 추가

src/commons/middlewares/crawling.ts, src/commons/middlewares/medicalOpenAPI.ts, src/commons/utils/kakao-map.service.ts, src/hospitals/controller/hospitals.controller.ts, src/hospitals/service/hospitals.service.ts, src/reports/reports.repository.ts
* `promises` 변수에 병렬처리된 데이터를 담아서 `await Promise.all(promises)` 코드에서 병렬처리가 완료되면 모든 데이터들을 담아서 `recommendedHospitals` 변수에 넣어줍니다.
* 카카오 API를 병원을 하나하나 돌면서 순차적으로 호출하는것이 아닌, 동시에 호출을 해서 값을 같이 받아오는 것입니다.
개선 전: ![](https://velog.velcdn.com/images/c1madang/post/ff7f086e-b98b-499b-8613-e104e145b918/image.png)
개선 후: ![스크린샷 2023-05-31 180518](https://github.com/project-codeblue/CodeBlue/assets/76824986/0b93a87c-91c9-42da-8bd6-1c946717b58b)
Related: #5
=> refactor: 카카오 API 병렬처리 후 성능 개선

src/commons/middlewares/crawling.ts, src/hospitals/service/hospitals.service.spec.ts, src/hospitals/service/hospitals.service.ts
- 본 기능은 성능 테스트 결과 기존 하버사인 방식과 큰 차이가 없기 때문에 코드 부분을 주석처리 했습니다.
- 본 방식을 사용하시려면 주석을 해제하시고 116~175번째 줄까지 주석처리 하시면 됩니다.
- 그 외 크롤링 timeout 설정 해제 및 기타 오류를 수정했습니다.
- hospitals service unit test 추가
=> feat: MySQL 공간 인덱스를 이용한 최단 거리 구현 및 일부 오류 수정

src/reports/service/reports.service.ts
- reports.service 코드에 일부 오류가 있어서 수정 및 전반적으로 리팩토링 했습니다.
=> refactor: 코드 리팩토링

src/commons/middlewares/crawling.ts, src/hospitals/controller/hospitals.controller.ts, src/hospitals/hospitals.repository.ts, src/hospitals/service/hospitals.service.ts, src/requests/requests.repository.ts, src/requests/service/requests.service.ts
* 병원 조회 API에서 반경 몇 km 병원을 조회하기를 원하는지와 몇 개 병원만을 가져올 지 query params로 넘겨주는 부분을 추가했습니다. 
* 종합 상황판에 없는 병원 데이터도 DB에서 지워줬습니다. 자세한 내용은 거리기반 병원 조회 성능 개선 페이지 트러블슈팅에서 보실 수 있습니다.
=> feat: 병원 조회 API 반경 몇 km & 최대 병원 개수 설정 query params

package-lock.json, package.json, src/hospitals/controller/hospitals.controller.ts, src/requests/requests.repository.ts, src/requests/service/requests.service.ts
- 검색 API의 repository에 있던 기존 QueryBuilder 코드와 비즈니스 로직들을 service로 이전하였습니다.
- hospital controller 수정 및 날짜 오류 수정했습니다.
=> refactor: 검색 API 코드 개선

src/hospitals/controller/hospitals.controller.ts, src/hospitals/hospitals.repository.ts, src/hospitals/service/hospitals.service.ts
[수정현황]
controller 불필요 url삭제
query로 위도 경도 받기
//parseFloat = 문자열을 부동 소수점 숫자로 변환
const startLat = parseFloat(queries['latitude']);
[진행 예정 사항]
unit test
=> feat: hospital service 구조 변경 : 권용재

src/hospitals/service/hospitals.service.ts
=> feat: add transaction

src/reports/reports.repository.ts
=> Test: report repository 수정

src/commons/middlewares/crawling.ts, src/requests/service/requests.service.ts
#59 
다음과 같은 사항을 구현 및 수정하였습니다.
- 증상 보고서 검색 시 결과가 없으면 404 NotFoundException 처리 구현
- 크롤링 코드 Refactoring
=> feat: 검색 결과 수정 및 에러 처리 적용

src/reports/service/reports.service.ts
=> feat: 증상보고서 에러 정보 수정

src/hospitals/hospitals.entity.ts, src/hospitals/hospitals.repository.ts, src/hospitals/service/hospitals.service.ts
**[긴급]**
기존 geohospital 테이블을 사용하던 Spatial Index 관련 기능들을 전부 hospitals 테이블로 이전하였습니다.
따라서 hospitals repository의 쿼리문도 일부 수정하였으니 확인 부탁드립니다.
또한, 현재 엔티티 변경으로 인해 각 조원 분들의 로컬 엔티티 파일이 상이함에 따라 DB 데이터간에 충돌이 발생할 여지가 있으니 해당 PR을 확인하시면 즉시 적용 부탁드립니다
=> !BREAKING CHANGE: hospitals 엔티티 변경 및 spatial Index 수정

src/commons/providers/typeorm-config.provider.ts, src/hospitals/hospitals.repository.ts, src/patients/controller/patients.controller.spec.ts, src/patients/controller/patients.controller.ts, src/patients/dto/create-patient.dto.ts, src/patients/patients.module.ts, src/patients/patients.repository.ts, src/patients/pipe/gender-from-rrn.pipe.ts, src/patients/service/patients.service.spec.ts, src/patients/service/patients.service.ts, src/reports/controller/reports.controller.ts, src/reports/dto/update-report.dto.ts, src/reports/reports.repository.ts, src/reports/service/reports.service.ts, src/requests/service/requests.service.ts
* 환자 정보 입력 API 완료하였고 transaction도 적용했습니다.
* 병훈님이 raw query로 수정해주신 부분에서 available_beds에 오탈자가 있어 수정 후 잘 작동하는 거 확인했습니다.
=> feat: 환자 정보 입력 API 완료

src/hospitals/hospitals.repository.ts, src/patients/controller/patients.controller.ts, src/patients/pipe/gender-from-rrn.pipe.ts, src/reports/controller/reports.controller.ts, src/reports/dto/update-report.dto.ts, src/reports/reports.repository.ts, src/reports/service/reports.service.ts, src/requests/controller/requests.controller.ts, src/requests/service/requests.service.ts
* 증상 보고서 철회 DELETE API를 만들었습니다.
* 증상 보고서 수정 PATCH API를 만들었습니다.
* 증상 보고서 신청 POST API는 기존엔 report 정보만 response되었는데 patient까지 join해서 response를 주었습니다.
Related: #68, #69
=> feat: 증상 보고서 철회 DELETE API & 증상 보고서 수정 PATCH API

src/hospitals/service/hospitals.service.ts, src/patients/service/patients.service.ts, src/reports/reports.repository.ts, src/reports/service/reports.service.ts, src/requests/service/requests.service.ts, test/app.e2e-spec.ts
* patients table 다시 추가하고 e2e test 재진행하였습니다.
* 증상 보고서 상세 조회 API & 검색 API & 이송 신청 API 버그 발견해서 수정했습니다.
* 유닛테스트에서는 각 레이어에 정의되어있는 함수 동작만 테스트했고 예외처리 & 에러에 대한 처리는 없어서 e2e에서 각 케이스별로 에러가 생기는 부분까지 확인하였습니다.
* 이송 신청서 입력 API 완료되는대로 e2e도 변경사항 반영해서 3차 완료 진행하면 될 것 같습니다.
Related: #60
=> test: e2e test 2차 완료

src/hospitals/service/hospitals.service.ts, src/reports/service/reports.service.ts
=> fix: 병원 조회 API caching radius & max_count 변경시 새로운 caching 만들기

public/css/index.css, src/app.controller.ts, src/hospitals/controller/hospitals.controller.ts, src/hospitals/hospitals.module.ts, src/hospitals/service/hospitals.service.ts, src/requests/controller/requests.controller.ts, views/index.ejs, views/recommendedHospitals.ejs, views/reportDetail.ejs, views/reportSearchEngine.ejs, views/searchResult.ejs
검색은 navbar 증상보고서 검색을 클릭해서 접속할 수 있습니다.
=> feat: 웹사이트 기본 구조

src/reports/controller/reports.controller.ts, src/reports/dto/create-report.dto.ts, views/createReport.ejs, views/index.ejs, views/reportDetail.ejs
* fetch 요청으로 증상보고서 입력 POST API와 연동을 하였습니다.
* 현재 POST API를 요청하면 아래 코드의 data에서 api return값을 가져올 수 있습니다. 여기서 report_id를 가져오시고 .then 내에서 또 다른 fetch 요청을 하셔서 병원 조회 API를 호출하여야합니다.
* 추가적으로 사용자 현재 위치 위도 경도를 가져와야 합니다. 그 부분은 용재님이 전에 구현하신적 있으시니 물어보시면 될 것 같습니다.
* 또한, max_count와 radius를 병원 조회 API 주소에서 query params로 받고 있기 때문에 그거에 대한 input도 들어가면 좋을 것 같습니다. 
* 병원 조회 API는 `localhost:3000/hospital/:report_id?latitude=37.1886258&longitude=127.0766825&radius=30&max_count=1`이고 max_count랑 radius 쿼리는 옵션값입니다.
=> fix: 환자 증상보고서 입력 POST 요청 연결 완료

views/createReport.ejs
=> fix: querySelector 버그 수정

src/reports/controller/reports.controller.ts, src/reports/service/reports.service.ts
- 주관식의 문장이 저장되도록 코드를 변경하였습니다
- 증상보고서 수정에서 응급도가 다시 계산되는 부분은 주석처리해놓았습니다 (report controller, service 두부분입니다!)
- 인공지능 삽입 이전이라 응급도는 임의로 1이 들어가도록 해놓았습니다
=> feat: mvp수정 객관식->주관식 입력

config/app.config.ts, config/redis.config.ts, src/hospitals/hospitals.module.ts, src/reports/service/reports.service.ts, src/requests/requests.module.ts, views/recommendedHospitals.ejs
* redislabs로 cloud redis를 연결하였습니다.
* AI flask server url을 config에 넣어서 환경변수화 해주었습니다.
* dotenv 파일 변경 슬랙 확인해주시면 됩니다.
=> feat: redis cloud 연결

src/requests/service/requests.service.ts, views/recommendedHospitals.ejs
* 이송신청 및 철회 버튼 누르면 cache가 지워지고 새로고침이 잘 되는지 재확인하였고 버그 수정하였습니다.
=> fix: FE 이송신청 & 철회시 cache 지워지고 새로고침

src/patients/pipe/patient-body-data-validation.pipe.ts, views/createReport.ejs, views/nearbyHospitals.ejs, views/recommendedHospitals.ejs, views/reportDetail.ejs, views/reportSearchEngine.ejs, views/searchResult.ejs
* FE footer 수정하였습니다.
* FE 위치 재반영 버튼을 제일 상단으로 올렸습니다.
=> style: FE footer 수정 & 위치 재반영 버튼

src/reports/controller/reports.controller.ts, src/reports/dto/create-report.dto.ts, src/reports/service/reports.service.ts, views/createReport.ejs
* createReport FE 페이지에 주민번호 14자리가 모두 입력되어야 이름 필드가 나타나도록 설정하였습니다.
* 증상보고서 생성 API 수정이 들어갔습니다.
=> fix: 증상보고서 입력시 이름 필드 추가
